"""
Django settings for Verbum project.
Generated by 'django-admin startproject' using Django 6.1.
For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
from pathlib import Path
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
# SECURITY WARNING: don't run with debug turned on in production!
# Esse código permite que o DEBUG seja alterado no Render
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'homePage',
	'accounts'
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'Verbum.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'Verbum.wsgi.application'
# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
	DATABASES = {
		'default': dj_database_url.parse(DATABASE_URL)
	}
else:
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.sqlite3',
			'NAME': BASE_DIR / 'db.sqlite3',
		}
	}
# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
# Configuração de sessão
# A sessão expira após 30 minutos de inatividade
SESSION_COOKIE_AGE = 1800
# Renova a sessão a cada requisição enquanto o usuário estiver ativo
SESSION_SAVE_EVERY_REQUEST = True
# Impede que JavaScript acesse diretamente o cookie de sessão
SESSION_COOKIE_HTTPONLY = True
# Configurações de segurança utilizadas apenas em produção.
# Em desenvolvimento local o DEBUG permanece True, funcionando com HTTP
if not DEBUG:
	# O user é redirecionado para https
	SECURE_SSL_REDIRECT = True
	SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
	# Faz o cookie de sessão ser enviado somente através de https
	SESSION_COOKIE_SECURE = True
	# Aplica a mesma proteção no cookie utilizado pelo CSRF do django
	CSRF_COOKIE_SECURE = True
# Tempo de validade do token de recuperação de senha
# 15 minutos = 900 segundos
PASSWORD_RESET_TIMEOUT = 900
CSRF_TRUSTED_ORIGINS = [
	origin.strip()
	for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
	if origin.strip()
]
# Registro de auditoria: eventos críticos de segurança vão para o arquivo verbum.log
# mode='a' significa que o sistema só acrescenta linhas novas e não apaga o histórico
LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	# Formato de cada linha: data, hora, nível e mensagem
	'formatters': {
		'audit': {
			'format': '{asctime} {levelname} {message}',
			'style': '{',
		},
	},
	# Destinos do log: arquivo na raiz do projeto e console (Render)
	'handlers': {
		'file': {
			'class': 'logging.FileHandler',
			'filename': BASE_DIR / 'verbum.log',
			'mode': 'a',
			'encoding': 'utf-8',
			'formatter': 'audit',
		},
		'console': {
			'class': 'logging.StreamHandler',
			'formatter': 'audit',
		},
	},
	# Os eventos saem do app accounts, no nível INFO
	'loggers': {
		'accounts': {
			'handlers': ['file', 'console'],
			'level': 'INFO',
			'propagate': False,
		},
	},
}
# Chave usada para criptografar os segredos totp
# Essa chave é fornecida pelo ambiente e não fica armazenada no código
VERBUM_ENCRYPTION_KEY = os.environ['VERBUM_ENCRYPTION_KEY']
# Login pela home, para o professor não cair em /accounts/login/
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/accounts/painel/"
LOGOUT_REDIRECT_URL = "/"
