# Generated by Django 6.1 on 2026-09-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
